### ISSUE TITLE
Last releases lack APK file

### ISSUE THREAD

**Issue by IzzySoft** [d4rken/rootvalidator#6]
Hi, and thanks for making your app available via Github! I've just noticed the last 2 releases lack the `.apk` file. Is there any reason behind that – or would you consider adding it again to the latest release? For [some background](https://android.izzysoft.de/repo/apk/eu.thedarken.rootvalidator), that would allow me automatically getting the always latest version :stuck_out_tongue_winking_eye:

**Comment by d4rken** [comment]
Done.

**Comment by IzzySoft** [comment]
Thanks a lot! Repo will update again tonight, and in that run grab the update (as it will for future versions if they're found there :)

**Comment by julienkrebs90** [comment]
#6
